### ISSUE TITLE
isPluggedIn always returns false on Android

### ISSUE THREAD

**Issue by michaelkoelewijn** [robinpowered/react-native-audio-jack#11]
**Current behaviour**
Using the following code the result is always false which makes it unusable on mount.
Event listener does work.

```
//Always returns false - even when headphone is plugged in
async componentDidMount() {
    const isPlugged = await AudioJackManager.isPluggedIn()
    console.log(isPlugged)
}
```

**Expected behaviour**
Return true when plugged in.
This does work as expected on iOS

Using React Native 0.59.9 with version 1.0.3 react-native-audio-jack

**Comment by yinghang** [comment]
What kind of headset do you have plugged in? USB-c or just wired?

**Comment by michaelkoelewijn** [comment]
> What kind of headset do you have plugged in? USB-c or just wired?

Just a regular 3.5mm jack - haven't tried USB-c as we do not have one.

**Comment by yinghang** [comment]
Whats the version of Android that you're running this on?

**Comment by michaelkoelewijn** [comment]
@yinghang Using Android 9 (build number 9.1.0.193)

**Comment by pca-homsi** [comment]
same issue

**Comment by yinghang** [comment]
Does your headset have microphones as well?

https://github.com/robinpowered/react-native-audio-jack/blob/master/android/src/main/java/com/robinpowered/AudioJack/AudioJackModule.java#L77

I haven't had the time to debug this but we're only checking for `TYPE_WIRED_HEADPHONES` here but if you modify it to include `TYPE_WIRED_HEADSET` it might solve the problem.

**Comment by pca-homsi** [comment]
yes it have a mic
note that the listener is working as it should

**Comment by michaelkoelewijn** [comment]
> Does your headset have microphones as well?
> 
> https://github.com/robinpowered/react-native-audio-jack/blob/master/android/src/main/java/com/robinpowered/AudioJack/AudioJackModule.java#L77
> 
> I haven't had the time to debug this but we're only checking for `TYPE_WIRED_HEADPHONES` here but if you modify it to include `TYPE_WIRED_HEADSET` it might solve the problem.

I have tried debugging AudioJackModule.java#77 and ```device.getType()``` returns TYPE_BUILTIN_EARPIECE (1) when it should return TYPE_WIRED_HEADSET or TYPE_WIRED_HEADPHONES.

Is this an issue in Android itself you think?

**Comment by yinghang** [comment]
https://developer.android.com/reference/android/media/AudioDeviceInfo

There are bunch of AudioDevice types, we only included `TYPE_WIRED_HEADPHONES` because it fits our use case but feel free to submit a PR.

**Comment by michaelkoelewijn** [comment]
Yes i've seen the list. After investigating i've found that the issue isn't the missing type (well, actually it is) but ```device.getType()``` returning ```TYPE_BUILTIN_EARPIECE``` when a headphone **is** connected. This means that adding the missing types will not yet work.

I'm 100% sure that a fix must be applied to #77 (add corresponding type) because i've tried a hard ```return true``` which set the correct status in Android. Matching the correct type is the problem now.

I wish i had more expertise in this field but java isn't my strong suit (this piece of code is actually the first java i've checked/debugged/written)

**Comment by michaelkoelewijn** [comment]
https://github.com/robinpowered/react-native-audio-jack/pull/12

I got it working!
Found out the always returning "TYPE_BUILDIN_EARPIECE" was an error on my part.
Also found out bluetooth devices can be added which was another problem i had with the package (https://github.com/robinpowered/react-native-audio-jack/issues/9)

This commit seems to fix both issues.

**Comment by christophermark** [comment]
Interesting stuff - I'm guessing the two different callbacks are based on the type of audio device that's plugged in. If you look closely, the headphone plug can have 3 or 4 sections, based on whether it has a microphone. I'm guessing that would be left audio, right audio, microphone, ground.

![image](https://user-images.githubusercontent.com/6303781/68961755-157f1300-07a1-11ea-96d0-5a41e750af0d.png)

**Comment by christophermark** [comment]
@michaelkoelewijn thanks for the PR - are we good to close this issue now?

**Comment by yinghang** [comment]
> Interesting stuff - I'm guessing the two different callbacks are based on the type of audio device that's plugged in. If you look closely, the headphone plug can have 3 or 4 sections, based on whether it has a microphone. I'm guessing that would be left audio, right audio, microphone, ground.
> 
> ![image](https://user-images.githubusercontent.com/6303781/68961755-157f1300-07a1-11ea-96d0-5a41e750af0d.png)

Good discovery Chris! Guess the electrical engineer in you is still doing great. 😛

**Comment by michaelkoelewijn** [comment]
Fun to see the microphone image!
I am closing the issue as this is now fixed 👍
