### ISSUE TITLE
Bluetooth headphone not found

### ISSUE THREAD

**Issue by michaelkoelewijn** [robinpowered/react-native-audio-jack#9]
The listener only recognises mini-jack input.
Bluetooth devices do not seem to work.

Is there any way possible to make this plugin work with bluetooth connected devices?

**Comment by RWOverdijk** [comment]
For iOS at least:

```swift
func bluetoothOrHeadphonesConnected() -> Bool {
  let outputs = AVAudioSession.sharedInstance().currentRoute.outputs

  for output in outputs {
    if output.portType == AVAudioSessionPortBluetoothA2DP ||
      output.portType == AVAudioSessionPortBluetoothHFP ||
      output.portType == AVAudioSessionPortBluetoothLE ||
      output.portType == AVAudioSessionPortHeadphones {
      return true
    }
  }

  return false
}
```

**Update:** This will however also think that car radios and bluetooth speakers are headphones. AS the name of this module suggests, it might not be suited for this functionality because "bluetooth headphones" aren't "audio jack" peripherals and those two can have separate use cases.

**Comment by RWOverdijk** [comment]
Why did you close this? 😄

**Comment by michaelkoelewijn** [comment]
> Why did you close this? 😄

Because you are completely right about this haha.

> AS the name of this module suggests, it might not be suited for this functionality because "bluetooth headphones" aren't "audio jack" peripherals and those two can have separate use cases.

**Comment by RWOverdijk** [comment]
https://github.com/react-native-community/react-native-device-info/issues/643 :)

**Comment by michaelkoelewijn** [comment]
https://github.com/robinpowered/react-native-audio-jack/pull/12

**Comment by RWOverdijk** [comment]
Low-key added this anyway. Awesome :)
